title: YuJia Su 
#logo:
description: "Skills<br>Clinical education.<br>MSK and sports injury.<br>Manual Therapy.<br>Return to sport/work.<br>Chronic pain management.<br>Exercise prescription.<br>Concussion Management.<br>Chronic condition management.<br>Sports tapping.<br>Acute inpatient.<br>Inpatient/Outpatient rehab.<br>Parkinson's exercise clinic.<br>Pulmonary exercise clinic.<br>Cardiorespiratory.<br>Marketing.<br>Patient booking/billing/follow-up.<br>15+ years of exercise and fitness<br>experience.<br>Software development background.<br>Competitive sport background"
show_downloads: false
#theme: jekyll-theme-minimal #use this for now, view more at pages.github.com/themes/
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
